In [88]:
import pandas as pd

- 다음 데이터를 활용하여 실습 문제를 해결하세요.
1. **DataFrame객체 생성 :** 위의 데이터를 사용해 DataFrame객체를 생성하세요.
2. **열과 행 선택**
    - `Name`과 `City` 열을 선택하여 출력하세요.
    - 나이가 30 이상인 행을 선택하여 출력하세요.
3. **행과 열 추가**
    - `Country` 열을 추가하고, 모두 'USA'로 설정하세요.
    - 새로운 행을 추가하세요. (Name: Frank, Age: 33, City: Seattle, Salary: 85000)
4. **데이터 삭제**
    - `Salary` 열을 삭제하세요.
    - 'David'가 있는 행을 삭제하세요.
5. **데이터 수정**
    - `Age`가 35 이상인 사람들의 `Salary`를 5% 증가시키세요.
    - 'Alice'의 `City`를 'Boston'으로 수정하세요.
6. **데이터 타입 변환**
    - `Age`와 `Salary`의 데이터 타입을 float로 변환하세요.

In [89]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 28],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'San Francisco'],
    'Salary' : [70000, 80000, 120000, 90000, 75000]
}

df = pd.DataFrame(data)
df

      Name  Age           City  Salary
0    Alice   25       New York   70000
1      Bob   30    Los Angeles   80000
2  Charlie   35        Chicago  120000
3    David   40        Houston   90000
4      Eve   28  San Francisco   75000

In [90]:
print(df['Name'],df['City'])

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: str 0         New York
1      Los Angeles
2          Chicago
3          Houston
4    San Francisco
Name: City, dtype: str

In [91]:
print(df[df['Age'] >= 30])

      Name  Age         City  Salary
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago  120000
3    David   40      Houston   90000

In [92]:
df["Country"] = ["USA","USA","USA","USA","USA"]
# df["Country"] = "USA" # 한번에 입력가능
df.loc[5] = ['Frank', 33, 'Seattle', 85000, "USA"]
df

      Name  Age           City  Salary Country
0    Alice   25       New York   70000     USA
1      Bob   30    Los Angeles   80000     USA
2  Charlie   35        Chicago  120000     USA
3    David   40        Houston   90000     USA
4      Eve   28  San Francisco   75000     USA
5    Frank   33        Seattle   85000     USA

In [93]:
df = df.drop("Salary", axis=1)
df

      Name  Age           City Country
0    Alice   25       New York     USA
1      Bob   30    Los Angeles     USA
2  Charlie   35        Chicago     USA
3    David   40        Houston     USA
4      Eve   28  San Francisco     USA
5    Frank   33        Seattle     USA

In [94]:
df['Name'] =='David'

0    False
1    False
2    False
3     True
4    False
5    False
Name: Name, dtype: bool

In [95]:
df = df[df['Name'] !='David'] # David 가 아닌행만 남기기
df

      Name  Age           City Country
0    Alice   25       New York     USA
1      Bob   30    Los Angeles     USA
2  Charlie   35        Chicago     USA
4      Eve   28  San Francisco     USA
5    Frank   33        Seattle     USA

In [96]:
df["Salary"] = [70000, 80000, 120000, 75000, 85000]

In [100]:
df.loc[df['Age'] >=35, "Salary"] = df["Salary"] * 1.05 
df

      Name   Age           City Country    Salary
0    Alice  25.0       New York     USA   70000.0
1      Bob  30.0    Los Angeles     USA   80000.0
2  Charlie  35.0        Chicago     USA  126000.0
4      Eve  28.0  San Francisco     USA   75000.0
5    Frank  33.0        Seattle     USA   85000.0

In [101]:
df.loc[df['Name'] == 'Alice', 'City'] = 'Boston'
df

      Name   Age           City Country    Salary
0    Alice  25.0         Boston     USA   70000.0
1      Bob  30.0    Los Angeles     USA   80000.0
2  Charlie  35.0        Chicago     USA  126000.0
4      Eve  28.0  San Francisco     USA   75000.0
5    Frank  33.0        Seattle     USA   85000.0

In [99]:
df['Age'] = df['Age'].astype(float)
df['Salary'] = df["Salary"].astype(float)
print(df.dtypes)

Name           str
Age        float64
City           str
Country        str
Salary     float64
dtype: object

### **[실습 1] 데이터 정리 및 전처리**

다음은 직장 내 직원 데이터입니다. 결측된 값들이 포함되어 있습니다. `Salary`와 `YearsAtCompany`의 결측값을 각 열의 평균값으로 채우세요.

In [2]:
import pandas as pd

In [29]:
employee_data = {
    'EmployeeID': [101, 102, 103, 104, 105],
    'Name': ['John', 'Emily', 'Sara', 'Tom', 'Anna'],
    'Department': ['HR', 'IT', 'Marketing', None, 'HR'],
    'Salary': [50000, 70000, None, 45000, 52000],
    'YearsAtCompany': [5, None, 8, 3, 4]
}

df = pd.DataFrame(employee_data)
df

   EmployeeID   Name Department   Salary  YearsAtCompany
0         101   John         HR  50000.0             5.0
1         102  Emily         IT  70000.0             NaN
2         103   Sara  Marketing      NaN             8.0
3         104    Tom        NaN  45000.0             3.0
4         105   Anna         HR  52000.0             4.0

In [31]:
df["Salary"].mean()

np.float64(54250.0)

In [32]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df['YearsAtCompany'] = df['YearsAtCompany'].fillna(df['YearsAtCompany'].mean())

df

   EmployeeID   Name Department   Salary  YearsAtCompany
0         101   John         HR  50000.0             5.0
1         102  Emily         IT  70000.0             5.0
2         103   Sara  Marketing  54250.0             8.0
3         104    Tom        NaN  45000.0             3.0
4         105   Anna         HR  52000.0             4.0

### [실습 2] **중복값 제거**

다음은 한 판매점의 제품 판매 기록입니다. 동일한 제품이 중복으로 기록되어 있습니다. 중복된 `ProductID`를 가진 제품의 중복된 행을 제거한 후, 가격을 기준으로 오름차순 정렬한다.

In [35]:
product_data = {
    'ProductID': [1, 2, 3, 1, 4, 2],
    'ProductName': ['Laptop', 'Mouse', 'Monitor', 'Laptop', 'Keyboard', 'Mouse'],
    'Price': [1200, 25, 300, 1150, 45, 22],
    'QuantitySold': [10, 100, 50, 8, 70, 120]
}

df = pd.DataFrame(product_data)
df

   ProductID ProductName  Price  QuantitySold
0          1      Laptop   1200            10
1          2       Mouse     25           100
2          3     Monitor    300            50
3          1      Laptop   1150             8
4          4    Keyboard     45            70
5          2       Mouse     22           120

In [34]:
df_sort = df.sort_values(by="Price")
df_sort =  df_sort.drop_duplicates("ProductID")

print(df_sort)

df_sort

   ProductID ProductName  Price  QuantitySold
5          2       Mouse     22           120
4          4    Keyboard     45            70
2          3     Monitor    300            50
3          1      Laptop   1150             8

   ProductID ProductName  Price  QuantitySold
5          2       Mouse     22           120
4          4    Keyboard     45            70
2          3     Monitor    300            50
3          1      Laptop   1150             8

In [ ]:
# 합쳐서도 가능

df = df.sort_values(by="Price").drop_duplicates("ProductID")
df

   ProductID ProductName  Price  QuantitySold
5          2       Mouse     22           120
4          4    Keyboard     45            70
2          3     Monitor    300            50
3          1      Laptop   1150             8

### [실습 3] **데이터 정렬**

다음은 자동차 모델별 성능 데이터를 포함하고 있습니다. `마력(horsepower)`을 기준으로 오름차순으로 데이터를 정렬한 후, `연비(mpg)`가 높은 상위 3개 자동차만 출력하세요.

In [26]:
car_data = {
    'Model': ['Sedan', 'SUV', 'Truck', 'Coupe', 'Convertible'],
    'Horsepower': [180, 250, 200, 170, 150],
    'MPG': [30, 20, 15, 35, 28],
    'Price': [30000, 45000, 40000, 28000, 32000]
}

df = pd.DataFrame(car_data)
df

         Model  Horsepower  MPG  Price
0        Sedan         180   30  30000
1          SUV         250   20  45000
2        Truck         200   15  40000
3        Coupe         170   35  28000
4  Convertible         150   28  32000

In [27]:
df = df.sort_values("Horsepower")
print(df)
df = df.nlargest(3,"MPG")
print(df)

         Model  Horsepower  MPG  Price
4  Convertible         150   28  32000
3        Coupe         170   35  28000
0        Sedan         180   30  30000
2        Truck         200   15  40000
1          SUV         250   20  45000
         Model  Horsepower  MPG  Price
3        Coupe         170   35  28000
0        Sedan         180   30  30000
4  Convertible         150   28  32000

### [실습 4] **데이터 필터링**

다음은 축구 선수들의 데이터를 나타냅니다. 필터링을 통해 포지션이 "Forward"이고, 나이가 30 이하인 선수만 출력하세요.

In [23]:
football_data = {
    'PlayerID': [201, 202, 203, 204, 205],
    'Name': ['Ronaldo', 'Messi', 'Neymar', 'Mbappe', 'Kane'],
    'Position': ['Forward', 'Forward', 'Midfielder', 'Forward', 'Forward'],
    'GoalsScored': [600, 700, 400, 150, 200],
    'Age': [35, 33, 29, 22, 27]
}

df = pd.DataFrame(football_data)
df

   PlayerID     Name    Position  GoalsScored  Age
0       201  Ronaldo     Forward          600   35
1       202    Messi     Forward          700   33
2       203   Neymar  Midfielder          400   29
3       204   Mbappe     Forward          150   22
4       205     Kane     Forward          200   27

In [24]:
df[(df["Position"] == "Forward") & (df["Age"] <= 30)]

   PlayerID    Name Position  GoalsScored  Age
3       204  Mbappe  Forward          150   22
4       205    Kane  Forward          200   27

## **[종합 실습 1] 상품 판매 데이터 분석**

다음은 한 전자상거래 사이트의 **상품 판매 데이터**입니다. 고객들이 특정 상품을 구매한 기록이 포함되어 있습니다. 데이터를 활용하여 아래의 문제를 해결하세요.


1. 총 구매금액 컬럼 Total(Quantity * Price)을 만들고, 각 고객(CustomerID)별로 총 구매 금액을 계산하세요..
2. `Laptop`을 구매한 고객들의 평균 구매 금액을 계산하세요.
3. 가장 많이 판매된 상품(상품 이름과 판매된 총 수량)을 구하세요.
4. `OrderDate`가 2024년 1월 10일 이후인 주문만 필터링하여 출력하세요.
5. `Product`별로 판매량과 총 판매 금액을 계산한 후, 이를 `총 판매금액` 기준으로 내림차순으로 정렬하여 출력하세요.

In [2]:
import pandas as pd

# 예시 상품 판매 데이터
sales_data = {
    'OrderID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Product': ['Laptop', 'Mouse', 'Laptop', 'Monitor', 'Mouse', 'Keyboard', 'Laptop', 'Mouse', 'Monitor', 'Keyboard'],
    'Quantity': [1, 2, 1, 1, 2, 1, 1, 3, 1, 1],
    'Price': [1200, 25, 1200, 300, 25, 100, 1200, 25, 300, 100],
    'CustomerID': [1001, 1002, 1001, 1003, 1004, 1002, 1001, 1003, 1005, 1002],
    'OrderDate': ['2024-01-05', '2024-01-06', '2024-01-07', '2024-01-10', '2024-01-12', '2024-01-15', '2024-01-18', '2024-01-20', '2024-01-22', '2024-01-25']
}
df_sales = pd.DataFrame(sales_data)
df_sales

   OrderID   Product  Quantity  Price  CustomerID   OrderDate
0      101    Laptop         1   1200        1001  2024-01-05
1      102     Mouse         2     25        1002  2024-01-06
2      103    Laptop         1   1200        1001  2024-01-07
3      104   Monitor         1    300        1003  2024-01-10
4      105     Mouse         2     25        1004  2024-01-12
5      106  Keyboard         1    100        1002  2024-01-15
6      107    Laptop         1   1200        1001  2024-01-18
7      108     Mouse         3     25        1003  2024-01-20
8      109   Monitor         1    300        1005  2024-01-22
9      110  Keyboard         1    100        1002  2024-01-25

In [3]:
#1. 총 구매금액 컬럼 Total(Quantity * Price)을 만들고,
# 각 고객(CustomerID)별로 총 구매 금액을 계산하세요.

df_sales['Total_Price'] = df_sales["Quantity"] * df_sales["Price"]
print(df_sales)

df_sales.groupby("CustomerID")["Total_Price"].sum()

   OrderID   Product  Quantity  Price  CustomerID   OrderDate  Total_Price
0      101    Laptop         1   1200        1001  2024-01-05         1200
1      102     Mouse         2     25        1002  2024-01-06           50
2      103    Laptop         1   1200        1001  2024-01-07         1200
3      104   Monitor         1    300        1003  2024-01-10          300
4      105     Mouse         2     25        1004  2024-01-12           50
5      106  Keyboard         1    100        1002  2024-01-15          100
6      107    Laptop         1   1200        1001  2024-01-18         1200
7      108     Mouse         3     25        1003  2024-01-20           75
8      109   Monitor         1    300        1005  2024-01-22          300
9      110  Keyboard         1    100        1002  2024-01-25          100

CustomerID
1001    3600
1002     250
1003     375
1004      50
1005     300
Name: Total_Price, dtype: int64

In [4]:
#2. Laptop을 구매한 고객들의 평균 구매 금액을 계산하세요.
df_sales["Total_Price"][df_sales["Product"] == "Laptop"].mean()
print(df_sales["Total_Price"][df_sales["Product"] == "Laptop"].mean())

1200.0

In [ ]:
df_sales.loc[df_sales["Product"] == "Laptop", "Total_Price"].mean()

np.float64(1200.0)

In [5]:
# 3. 가장 많이 판매된 상품(상품 이름과 판매된 총 수량)을 구하세요
# 내풀이
best_product = df_sales.groupby("Product")["Quantity"].sum()

best_product.sort_values(ascending=False,inplace=True)
best_product.head(1)

Product
Mouse    7
Name: Quantity, dtype: int64

In [6]:
print(best_product.idxmax(),best_product.max())

Mouse 7

In [ ]:
# 4. OrderDate가 2026년 1월 10일 이후인 주문만 필터링하여 출력하세요.
df_sales

   OrderID   Product  Quantity  Price  CustomerID   OrderDate  Total_Price
0      101    Laptop         1   1200        1001  2024-01-05         1200
1      102     Mouse         2     25        1002  2024-01-06           50
2      103    Laptop         1   1200        1001  2024-01-07         1200
3      104   Monitor         1    300        1003  2024-01-10          300
4      105     Mouse         2     25        1004  2024-01-12           50
5      106  Keyboard         1    100        1002  2024-01-15          100
6      107    Laptop         1   1200        1001  2024-01-18         1200
7      108     Mouse         3     25        1003  2024-01-20           75
8      109   Monitor         1    300        1005  2024-01-22          300
9      110  Keyboard         1    100        1002  2024-01-25          100

In [ ]:
df_sales[df_sales["OrderDate"] > '2024-01-10']

   OrderID   Product  Quantity  Price  CustomerID   OrderDate  Total_Price
4      105     Mouse         2     25        1004  2024-01-12           50
5      106  Keyboard         1    100        1002  2024-01-15          100
6      107    Laptop         1   1200        1001  2024-01-18         1200
7      108     Mouse         3     25        1003  2024-01-20           75
8      109   Monitor         1    300        1005  2024-01-22          300
9      110  Keyboard         1    100        1002  2024-01-25          100

In [ ]:
# 5. Product별로 판매량과 총 판매 금액을 계산한 후, 
# 이를 총 판매금액 기준으로 내림차순으로 정렬하여 출력하세요.

df_sales.groupby("Product")[["Quantity","Total_Price"]].sum().sort_values(by="Total_Price",ascending=False)

          Quantity  Total_Price
Product
Laptop           3         3600
Monitor          2          600
Keyboard         2          200
Mouse            7          175

## [종합 실습 2] **컨텐츠 선호 데이터 분석**

다음은 사용자가 다양한 컨텐츠를 평가한 **컨텐츠 선호 데이터**입니다. 사용자가 영화, 음악, 책 등을 평가한 데이터를 바탕으로 분석을 수행하세요.

In [9]:
# 예시 컨텐츠 선호 데이터
preference_data = {
    'UserID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'ContentID': [101, 102, 101, 103, 104, 105, 106, 101, 107, 102],
    'ContentType': ['Movie', 'Music', 'Movie', 'Book', 'Movie', 'Music', 'Book', 'Movie', 'Music', 'Book'],
    'Rating': [5, 3, 4, 2, 5, 4, 3, 4, 5, 2],
    'ReviewDate': ['2026-07-01', '2026-07-02', '2026-07-03', '2026-07-05', '2026-07-07', '2026-07-10', '2026-07-12', '2026-07-14', '2026-07-15', '2026-07-20']
}
df_preference = pd.DataFrame(preference_data)
df_preference

   UserID  ContentID ContentType  Rating  ReviewDate
0       1        101       Movie       5  2026-07-01
1       2        102       Music       3  2026-07-02
2       3        101       Movie       4  2026-07-03
3       4        103        Book       2  2026-07-05
4       5        104       Movie       5  2026-07-07
5       6        105       Music       4  2026-07-10
6       7        106        Book       3  2026-07-12
7       8        101       Movie       4  2026-07-14
8       9        107       Music       5  2026-07-15
9      10        102        Book       2  2026-07-20

1. 각 컨텐츠 타입(`ContentType`)별로 평균 평점을 계산하세요.
2. 가장 높은 평점을 받은 `ContentID`와 해당 평점을 구하세요.
3. `Movie` 유형 컨텐츠에 대해 평점이 4 이상인 사용자들의 데이터를 필터링하세요.
4. `ReviewDate`가 2026년 7월 10일 이후인 리뷰 중에서 `Rating`이 4 이상인 데이터를 필터링하여 출력하세요.
5. 각 컨텐츠별(`ContentID`) 평가한  유저수를 계산하고, 이를 출력하세요.

In [10]:
# 1. 각 컨텐츠 타입(ContentType)별로 평균 평점을 계산하세요.
df_preference.groupby("ContentType")["Rating"].mean()

ContentType
Book     2.333333
Movie    4.500000
Music    4.000000
Name: Rating, dtype: float64

In [15]:
# 2. 가장 높은 평점을 받은 ContentID와 해당 평점을 구하세요.
max_rating = df_preference["Rating"].max()

df_preference.loc[df_preference["Rating"] == max_rating]

max_rating_contents = df_preference.loc[
    df_preference["Rating"] == max_rating
]
max_rating_contents

   UserID  ContentID ContentType  Rating  ReviewDate
0       1        101       Movie       5  2026-07-01
4       5        104       Movie       5  2026-07-07
8       9        107       Music       5  2026-07-15

In [17]:
# 3. Movie 유형 컨텐츠에 대해 평점이 4 이상인 사용자들의 데이터를 필터링하세요.

df_preference[(df_preference["ContentType"] == "Movie") & (df_preference["Rating"] >=4)]

   UserID  ContentID ContentType  Rating  ReviewDate
0       1        101       Movie       5  2026-07-01
2       3        101       Movie       4  2026-07-03
4       5        104       Movie       5  2026-07-07
7       8        101       Movie       4  2026-07-14

In [18]:
# 4. ReviewDate가 2026년 7월 10일 이후인 리뷰 중에서 
# Rating이 4 이상인 데이터를 필터링하여 출력하세요.

df_preference[(df_preference["ReviewDate"] > "2026-07-10") & (df_preference["Rating"] >=4)]

   UserID  ContentID ContentType  Rating  ReviewDate
7       8        101       Movie       4  2026-07-14
8       9        107       Music       5  2026-07-15

In [20]:
# 5. 각 컨텐츠별(ContentID) 평가한  유저수를 계산하고, 이를 출력하세요.
df_preference.groupby("ContentID")['UserID'].count()

ContentID
101    3
102    2
103    1
104    1
105    1
106    1
107    1
Name: UserID, dtype: int64